spring:
  cloud:
    kubernetes:
      config:
        enabled: true
        sources:
          - namespace: default
            name: two-api-service
      reload:
        enabled: true
        mode: event