apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30002
