spring:
  cloud:
    gateway:
      routes:
        - id: one_route
          uri: http://one-api-svc:8080
          predicates:
            - Path=/one/**
        - id: two_route
          uri: http://two-api-svc:8080
          predicates:
            - Path=/two/**
    kubernetes:
      config:
        enabled: false
      discovery:
        enabled: true