apiVersion: v1
kind: Service
metadata:
  name: one-api-svc
spec:
  type: NodePort
  selector:
    app: one-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
