apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-api-deployment
  labels:
    app: two-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-api-deployment
  template:
    metadata:
      labels:
        app: two-api-deployment
    spec:
      containers:
        - name: two-api-deployment
          image: 692609349536.dkr.ecr.ap-northeast-2.amazonaws.com/spring-cloud-example
          imagePullPolicy: Always
          command: [ "java" ]
          args: [ "-jar", "two-api/build/libs/app.jar" ]
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "Asia/Seoul"