apiVersion: v1
kind: Service
metadata:
  name: two-api-svc
spec:
  type: NodePort
  selector:
    app: two-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
